#! /bin/bash

set -e
set -u
set -x

OMERO_VERSION=${OMERO_VERSION:-5.4.0}

pip install omego

# to avoid error message
pip install "numpy>=1.9"
pip install "Pillow<3.4"

# Install the server
omego install --managedb --dbhost localhost --dbname omero --prestartfile $HOME/config.omero -v --release $OMERO_VERSION --ice 3.5 --no-web


OMERO.server/bin/omero admin diagnostics;
# run the tests
VALUE=$(readlink -f OMERO.server)
# remove the scripts and copy the modified scripts
rm -rf $VALUE/lib/scripts/omero
cp -r omero $VALUE/lib/scripts
export PYTHONPATH=$VALUE/lib/python
python setup.py test -t test/integration -i $VALUE/etc/ice.config -v
